cabal-version:      3.0
name:               ghc-quickfix
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Aaron Allen
maintainer:         aaronallen8455@gmail.com
-- copyright:
category:           Development
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  GhcQuickfix
    other-modules: GhcQuickfix.GhcFacade
    -- other-extensions:
    build-depends:    base,
                      ghc,
                      text,
                      async,
                      stm-containers,
                      directory,
                      stm,
                      deferred-folds,
                      foldl
    hs-source-dirs:   src
    default-language: GHC2021

test-suite ghc-quickfix-test
    import:           warnings
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base,
        ghc-quickfix

executable play
    import:           warnings
    default-language: GHC2021
    hs-source-dirs:   play
    main-is:          Main.hs
    build-depends:
        base,
        ghc-quickfix
    ghc-options: -fplugin GhcQuickfix
