cabal-version:      3.0
name:               test-modules
version:            0.1.0.0
extra-source-files:
  *.expected

common attrs
    build-depends:    base,
                      ghci-quickfix
    hs-source-dirs:   .
    default-language: GHC2021

executable ParseError1
    import: attrs
    main-is: ParseError1.hs
    ghc-options: -fplugin GhciQuickfix -fplugin-opt GhciQuickfix:--quickfix-file=ParseError1.qf

executable TypeErr1
    import: attrs
    main-is: TypeErr1.hs
    ghc-options: -fplugin GhciQuickfix -fplugin-opt GhciQuickfix:--quickfix-file=TypeErr1.qf

executable UnusedVar
    import: attrs
    main-is: UnusedVar.hs
    ghc-options: -fplugin GhciQuickfix -fplugin-opt GhciQuickfix:--quickfix-file=UnusedVar.qf -Wall

executable IncompletePat
    import: attrs
    main-is: IncompletePat.hs
    ghc-options: -fplugin GhciQuickfix -fplugin-opt GhciQuickfix:--quickfix-file=IncompletePat.qf -Wincomplete-patterns

executable MultiMod
    import: attrs
    main-is: MultiMod1.hs
    other-modules: MultiMod2
    ghc-options: -fplugin GhciQuickfix -fplugin-opt GhciQuickfix:--quickfix-file=MultiMod.qf -Wall

executable WarningFix
    import: attrs
    main-is: WarningFix1.hs
    other-modules: WarningFix2
    ghc-options: -fplugin GhciQuickfix -fplugin-opt GhciQuickfix:--quickfix-file=WarningFix.qf -Wall
